"""Grade 2 — operators + arithmetic mastery, taught through fox-grapes.

Grade 2 deepens grade 1's L1+L2 work. Where grade 1 introduced the
single-arg arithmetic call, grade 2 covers multi-arg arithmetic,
comparison chains, the boolean-logic operators, the numeric helpers
(inc/dec/quot/rem/mod, min/max, abs), strings via str, and the
truthy/falsey rules.

The fable lens: the hasty fox's rationalizing dismissals about
answers ('that cluster is too high to bother evaluating!')
consistently lose to the patient fox's disciplined
"let me actually evaluate the form" approach. By grade 2, this becomes
the running joke of the curriculum.
"""
from __future__ import annotations

from mmllm.aesop.curriculum.generator import (
    SubjectCurriculum, SubjectExample, SubplotTemplate,
)
from mmllm.aesop.curriculum.fox_grapes.grade_1 import (
    _SHARED_SUBPLOTS as _G1_SHARED_SUBPLOTS,
    _PLAN_POOL,
)
from mmllm.aesop.curriculum.fox_grapes._metaphor_pools import (
    _ACORN_SUBPLOTS,
    _BASKET_SUBPLOTS,
    _BEADSTRING_SUBPLOTS,
    _CHALKMARK_SUBPLOTS,
    _GATE_SUBPLOTS,
    _SCRIBE_SUBPLOTS,
    _TALLYWALK_SUBPLOTS,
)


# Extend grade-1's shared pool with two grade-2-specific subplots
# that lean into multi-operand / chained-operator framings.
_SHARED_SUBPLOTS: list[SubplotTemplate] = list(_G1_SHARED_SUBPLOTS) + [
    # 9. The chain-of-operations template — useful for multi-arg
    #    arithmetic and comparison-chain subjects.
    SubplotTemplate("""\
{patient_fox_phrase} had been laying out a chain of small computations on
a slate {place} — one operation, then another, all to settle a
question {hasty_fox_phrase} had raised. The current form on the slate was
{form_display}, and {patient_fox} explained that {concept_phrase} would
be settled the moment the form was evaluated."""),

    # 10. The wager-with-stakes template — increases the dramatic stakes
    #     when the form is more interesting (e.g., min/max, mod).
    SubplotTemplate("""\
"Whatever {form_display} comes to," {hasty_fox_phrase} declared, {emo_proud}
{place}, "I'll wager I know it without typing it." {patient_fox_phrase},
{emo_patient}, picked up a twig and drew {concept_phrase} in the
dust. "Then write the form," {patient_fox_he_she} said. "The REPL will
have the last word.\""""),
]


def _ex(form, expected, concept, what,
        goal="", scenario="", need="", mapping="", resolution="",
        tags=()):
    return SubjectExample(form=form, expected=expected,
                          concept_phrase=concept, question_what=what,
                          goal_text=goal,
                          scenario=scenario, need=need,
                          mapping=mapping, resolution=resolution,
                          tags=tags)


# ─────────────────────── 22 grade-2 subjects ───────────────────────


G2_01 = SubjectCurriculum(
    grade=2, subject_id="G2-01",
    subject_title="Multi-arg arithmetic",
    fable="fox-grapes",
    examples=[
        _ex("(+ 1 2 3 4)",
            10,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(* 2 3 4)",
            24,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(- 100 1 2 3)",
            94,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(+ 1 2 3 4 5 6 7 8 9 10)",
            55,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(* 1 2 3 4 5)",
            120,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(+ 10 20 30)",
            60,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
    ],
    subplots=_ACORN_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_02 = SubjectCurriculum(
    grade=2, subject_id="G2-02",
    subject_title="Comparison chains",
    fable="fox-grapes",
    examples=[
        _ex("(< 1 2 3)",
            True,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(< 3 2 1)",
            False,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(<= 1 1 2)",
            True,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(> 5 4 3 2 1)",
            True,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(>= 3 3 2)",
            True,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",))  ],
    subplots=_ACORN_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_03 = SubjectCurriculum(
    grade=2, subject_id="G2-03",
    subject_title="not= and = with multiple args",
    fable="fox-grapes",
    examples=[
        _ex("(not= 1 2)",
            True,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(not= 1 1)",
            False,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(= 1 1 1)",
            True,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(= 1 1 2)",
            False,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(not= 1 1 2)",
            True,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
    ],
    subplots=_ACORN_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_04 = SubjectCurriculum(
    grade=2, subject_id="G2-04",
    subject_title="min and max",
    fable="fox-grapes",
    examples=[
        _ex("(min 1 2 3)",
            1,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(max 1 2 3)",
            3,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(min 7 3 9 1 5)",
            1,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(max 7 3 9 1 5)",
            9,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(min -3 -1 -5)",
            -5,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
    ],
    subplots=_ACORN_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_05 = SubjectCurriculum(
    grade=2, subject_id="G2-05",
    subject_title="quot, rem, mod",
    fable="fox-grapes",
    examples=[
        _ex("(quot 17 5)",
            3,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(rem 17 5)",
            2,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(mod 17 5)",
            2,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(quot 100 7)",
            14,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(rem 100 7)",
            2,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(mod -7 3)",
            2,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
    ],
    subplots=_ACORN_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_06 = SubjectCurriculum(
    grade=2, subject_id="G2-06",
    subject_title="inc and dec",
    fable="fox-grapes",
    examples=[
        _ex("(inc 5)",
            6,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(dec 5)",
            4,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(inc 0)",
            1,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(dec 0)",
            -1,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(inc -1)",
            0,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
    ],
    subplots=_ACORN_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_07 = SubjectCurriculum(
    grade=2, subject_id="G2-07",
    subject_title="Absolute value",
    fable="fox-grapes",
    examples=[
        _ex("(abs 5)",
            5,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(abs -5)",
            5,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(abs 0)",
            0,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(abs (- 3 8))",
            5,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
    ],
    subplots=_ACORN_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_08 = SubjectCurriculum(
    grade=2, subject_id="G2-08",
    subject_title="Arithmetic on ratios",
    fable="fox-grapes",
    examples=[
        _ex("(+ 1/2 1/4)",
            "3/4",
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(* 2/3 3/4)",
            "1/2",
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(- 1 1/3)",
            "2/3",
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
    ],
    subplots=_ACORN_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_09 = SubjectCurriculum(
    grade=2, subject_id="G2-09",
    subject_title="Floats vs ints (the / operator)",
    fable="fox-grapes",
    examples=[
        _ex("(/ 10 2)",
            5,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(/ 10 3)",
            "10/3",
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(/ 1.0 2)",
            0.5,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
    ],
    subplots=_ACORN_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_10 = SubjectCurriculum(
    grade=2, subject_id="G2-10",
    subject_title="Powers via repeated multiplication",
    fable="fox-grapes",
    examples=[
        _ex("(* 2 2 2)",
            8,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(* 5 5)",
            25,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(* 3 3 3 3)",
            81,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(* 10 10)",
            100,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
    ],
    subplots=_ACORN_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_11 = SubjectCurriculum(
    grade=2, subject_id="G2-11",
    subject_title="String concatenation with str",
    fable="fox-grapes",
    examples=[
        _ex('(str "gra" "pes")', "grapes",
            'the form (str "gra" "pes")', 'the joined string "grapes"'),
        _ex('(str "vine")', "vine",
            'the form (str "vine")', 'the value of (str "vine")'),
        _ex('(str "x" "y" "z")',
            "xyz",
            'the three-arg concatenation of single-character strings',
            'the joined cord the three single-letter strings produce',
            goal='concatenate three single-character strings into one',
            scenario="Sly the fox had three short cords of lettered beads on the market-fox's counting-table, each cord just one letter long. The cords sat side by side, ready to be tied head-to-tail in order.",
            need="Sly wanted one continuous cord — the three cords' beads in the order they were laid out, threaded into a single string.",
            mapping="The str form ties cords end-to-end: each argument is a cord of beads, and the result is one long cord. The first arg's beads come first; the next arg's are knotted to its tail; the third's to that tail in turn.",
            resolution='the joined cord carried all three letters in their original order, head-to-tail in one piece, and Sly hung it from the stall.',
            tags=("story",)),
        _ex('(str 1 "+" 2 "=" 3)',
            "1+2=3",
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Vix the fox laid out cords of lettered beads on the market-fox's counting-table, ready to be threaded or sliced.",
            need="Vix wanted the form's transformation applied to the cord — joined, sliced, or counted as the form said.",
            mapping='Strings in Clojure are cords of beads: joining ties cords end-to-end; slicing cuts a section; counting returns the bead-total.',
            resolution='the cord came back transformed as the form had directed — joined, sliced, or counted as asked.',
            tags=("story",)),
    ],
    subplots=_BEADSTRING_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_12 = SubjectCurriculum(
    grade=2, subject_id="G2-12",
    subject_title="print and println — return values",
    fable="fox-grapes",
    examples=[
        # println side-effects to stdout but RETURNS nil. The form
        # we ask for has the value nil; the model writes println
        # and the runtime returns nil.
        _ex('(println "hello")',
            None,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Sly the fox wrote a fresh entry in the leather ledger — marginalia, whitespace, and a form, all set out by scribe's conventions.",
            need="Sly wanted the form's value, with the marginalia preserved for the next reader.",
            mapping='Comments, whitespace, and reader macros are scribe conventions: the runtime ignores them, but the reader uses them for context.',
            resolution='the form returned its honest value, and the marginalia stayed in the ledger margin for the next reader.',
            tags=("story",)),
        _ex('(print "x")',
            None,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Renard the fox wrote a fresh entry in the leather ledger — marginalia, whitespace, and a form, all set out by scribe's conventions.",
            need="Renard wanted the form's value, with the marginalia preserved for the next reader.",
            mapping='Comments, whitespace, and reader macros are scribe conventions: the runtime ignores them, but the reader uses them for context.',
            resolution='the form returned its honest value, and the marginalia stayed in the ledger margin for the next reader.',
            tags=("story",)),
    ],
    subplots=_SCRIBE_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_13 = SubjectCurriculum(
    grade=2, subject_id="G2-13",
    subject_title="and / or — short circuit, return values",
    fable="fox-grapes",
    examples=[
        _ex("(and true true)",
            True,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Vix the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Vix needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(and true false)",
            False,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Sly the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Sly needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(or false true)",
            True,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Renard the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Renard needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(or false false)",
            False,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Vix the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Vix needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(and 1 2 3)",
            3,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Sly the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Sly needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(or nil false 5)",
            5,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Renard the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Renard needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
    ],
    subplots=_GATE_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_14 = SubjectCurriculum(
    grade=2, subject_id="G2-14",
    subject_title="not — turning truthy to false",
    fable="fox-grapes",
    examples=[
        _ex("(not true)",
            False,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Vix the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Vix needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(not false)",
            True,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Sly the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Sly needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(not nil)",
            True,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Renard the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Renard needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(not 0)",
            False,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Vix the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Vix needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(not \"\")",
            False,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Sly the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Sly needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
    ],
    subplots=_GATE_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_15 = SubjectCurriculum(
    grade=2, subject_id="G2-15",
    subject_title="Falsey values: only false and nil",
    fable="fox-grapes",
    examples=[
        _ex("(if 0 :truthy :falsey)",
            ":truthy",
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Renard the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Renard needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(if \"\" :truthy :falsey)",
            ":truthy",
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Vix the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Vix needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(if nil :truthy :falsey)",
            ":falsey",
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Sly the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Sly needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(if false :truthy :falsey)",
            ":falsey",
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Renard the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Renard needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
    ],
    subplots=_GATE_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_16 = SubjectCurriculum(
    grade=2, subject_id="G2-16",
    subject_title="Truthy 0 and empty string",
    fable="fox-grapes",
    examples=[
        _ex("(boolean 0)",
            True,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Vix the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Vix needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(boolean \"\")",
            True,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Sly the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Sly needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(boolean nil)",
            False,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Renard the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Renard needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
        _ex("(boolean false)",
            False,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Vix the fox stood at the orchard gate. Its latches lifted only when the form's verdict said so.",
            need="Vix needed the latches' yes-or-no answer for the form's question — open or closed, nothing in between.",
            mapping="Boolean predicates decide the latches' fate. `and` requires every latch lifted; `or` lets either open the gate; the verdict is the latch's state, not the values it weighed.",
            resolution="the latches gave their verdict, and the gate's response matched the form's honest predicate.",
            tags=("story",)),
    ],
    subplots=_GATE_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_17 = SubjectCurriculum(
    grade=2, subject_id="G2-17",
    subject_title="Keyword as function for map lookup",
    fable="fox-grapes",
    examples=[
        _ex("(:fox {:fox 1 :grapes 2})",
            1,
            'the keyword-as-function lookup at the :fox slot',
            'the value at the :fox slot of the small market-tray',
            goal='look up the value at key :fox in a small map keyed by :fox and :grapes',
            scenario="Vix the fox kept a small market-tray with two named slots: one labeled :fox for the day's pickings and another labeled :grapes for the press's set-aside. Each label held its own tally; she could read either by pointing to its slot.",
            need='Vix wanted the value sitting in the :fox slot — what the day had brought in for her own count. Reaching for the :grapes slot would give her a different number.',
            mapping='A keyword used as a function reads its own slot from the tray. The keyword names the slot; the map is the tray; the REPL fetches the value at the labeled compartment.',
            resolution="the :fox slot yielded its tally, exactly the day's own count, and Vix wrote it down on her parchment.",
            tags=("story",)),
        _ex("(:grapes {:fox 1 :grapes 2})",
            2,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Sly the fox laid out a vine-tray with named compartments at the press, the day's pickings sorted by their labels.",
            need='Sly reached into the right slot to read what the tray held there, leaving the rest untouched.',
            mapping="A collection in Clojure is a labeled tray. Looking up by key reads the value at that slot; the tray's other slots stay closed.",
            resolution="the slot yielded its value, and their parchment recorded the day's count for that label.",
            tags=("story",)),
        _ex("(:missing {:fox 1})",
            None,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Renard the fox laid out a vine-tray with named compartments at the press, the day's pickings sorted by their labels.",
            need='Renard reached into the right slot to read what the tray held there, leaving the rest untouched.',
            mapping="A collection in Clojure is a labeled tray. Looking up by key reads the value at that slot; the tray's other slots stay closed.",
            resolution="the slot yielded its value, and his parchment recorded the day's count for that label.",
            tags=("story",)),
    ],
    subplots=_BASKET_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_18 = SubjectCurriculum(
    grade=2, subject_id="G2-18",
    subject_title="Quoting symbols",
    fable="fox-grapes",
    examples=[
        _ex("(quote fox)", "fox", "the quoted symbol (quote fox)",
            "the value of (quote fox)"),
        _ex("'grapes", "grapes", "the quoted symbol 'grapes",
            "the value of 'grapes"),
        _ex("'(1 2 3)",
            [1, 2, 3],
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox had chalked a tag onto a vine-post — the name, not the cluster behind it.',
            need="Vix wanted to ask the form a question about the tag's nature, not about what the tag named.",
            mapping='`quote` sets a token aside as a name, not a value to evaluate. Symbol predicates ask of any token: is this one of those name-tokens?',
            resolution='the form returned the verdict the predicate had asked of the tag — name or value, drawn cleanly.',
            tags=("story",)),
    ],
    subplots=_CHALKMARK_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_19 = SubjectCurriculum(
    grade=2, subject_id="G2-19",
    subject_title="Auto-promotion to bigint",
    fable="fox-grapes",
    examples=[
        _ex("(* 1000000 1000000)",
            1000000000000,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(+ 99999999999 1)",
            100000000000,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
    ],
    subplots=_ACORN_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_20 = SubjectCurriculum(
    grade=2, subject_id="G2-20",
    subject_title="Counting",
    fable="fox-grapes",
    examples=[
        _ex("(count [1 2 3])",
            3,
            'the length of a small vector',
            "the row's tick-total after the tally-walk",
            goal='count the items in a small vector',
            scenario='Vix the fox walked the vine-row with a slate, ticking off each cluster as she passed it. The row carried three clusters this morning — she would walk it once and report the tally at the end.',
            need="She wanted the row's length — not which clusters were there, just how many — landing on the slate as a single honest number.",
            mapping="The count form is the tally-walk: it visits each item in the collection once, ticking the slate, and returns the tick-total. The walk is the operation; the slate's final number is the return value.",
            resolution="the slate at the row's end held the row's length — Vix's honest tick-count, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(count \"hello\")",
            5,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox walked the vine-row with a slate, ticking off each cluster as her passed it.',
            need="Vix wanted the row's length or running total — a single honest number when the walk ended.",
            mapping='`reduce` and `count` are the tally-walk: visit each item once, tick or accumulate, return the final total.',
            resolution="the slate at the row's end held the honest tally — exactly what the walk had produced.",
            tags=("story",)),
        _ex("(count [])",
            0,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox walked the vine-row with a slate, ticking off each cluster as their passed it.',
            need="Sly wanted the row's length or running total — a single honest number when the walk ended.",
            mapping='`reduce` and `count` are the tally-walk: visit each item once, tick or accumulate, return the final total.',
            resolution="the slate at the row's end held the honest tally — exactly what the walk had produced.",
            tags=("story",)),
    ],
    subplots=_TALLYWALK_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_21 = SubjectCurriculum(
    grade=2, subject_id="G2-21",
    subject_title="String length and substring",
    fable="fox-grapes",
    examples=[
        _ex("(count \"grapes\")",
            6,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Renard the fox laid out cords of lettered beads on the market-fox's counting-table, ready to be threaded or sliced.",
            need="Renard wanted the form's transformation applied to the cord — joined, sliced, or counted as the form said.",
            mapping='Strings in Clojure are cords of beads: joining ties cords end-to-end; slicing cuts a section; counting returns the bead-total.',
            resolution='the cord came back transformed as the form had directed — joined, sliced, or counted as asked.',
            tags=("story",)),
        _ex("(count \"fox\")",
            3,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Vix the fox laid out cords of lettered beads on the market-fox's counting-table, ready to be threaded or sliced.",
            need="Vix wanted the form's transformation applied to the cord — joined, sliced, or counted as the form said.",
            mapping='Strings in Clojure are cords of beads: joining ties cords end-to-end; slicing cuts a section; counting returns the bead-total.',
            resolution='the cord came back transformed as the form had directed — joined, sliced, or counted as asked.',
            tags=("story",)),
        _ex("(subs \"grapes\" 0 3)",
            "gra",
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario="Sly the fox laid out cords of lettered beads on the market-fox's counting-table, ready to be threaded or sliced.",
            need="Sly wanted the form's transformation applied to the cord — joined, sliced, or counted as the form said.",
            mapping='Strings in Clojure are cords of beads: joining ties cords end-to-end; slicing cuts a section; counting returns the bead-total.',
            resolution='the cord came back transformed as the form had directed — joined, sliced, or counted as asked.',
            tags=("story",)),
    ],
    subplots=_BEADSTRING_SUBPLOTS, plan_pool=_PLAN_POOL,
)


G2_22 = SubjectCurriculum(
    grade=2, subject_id="G2-22",
    subject_title="Compose pure arithmetic (multi-step calculation)",
    fable="fox-grapes",
    examples=[
        # A simple reach: jumps × height per jump, then minus a shortfall.
        _ex("(- (* 5 4) 7)",
            13,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Renard the fox tallied small heaps of clusters on a slate at the press.',
            need="Renard wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(+ (* 3 8) (* 2 4))",
            32,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Vix the fox tallied small heaps of clusters on a slate at the press.',
            need="Vix wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
        _ex("(quot (+ 100 50) 5)",
            30,
            'a form',
            'the value the form evaluates to',
            goal='evaluate this form',
            scenario='Sly the fox tallied small heaps of clusters on a slate at the press.',
            need="Sly wanted the slate's running total — what the form's arithmetic would produce for that day's heaps.",
            mapping='Arithmetic in Clojure is the slate-tally: the form names the operation, the args are the heaps, and the REPL counts out the result.',
            resolution="the slate held the value the form's tally produced, ready to be posted to the day's harvest log.",
            tags=("story",)),
    ],
    subplots=_ACORN_SUBPLOTS, plan_pool=_PLAN_POOL,
)


SUBJECTS: dict[str, SubjectCurriculum] = {
    s.subject_id: s for s in (
        G2_01, G2_02, G2_03, G2_04, G2_05, G2_06, G2_07, G2_08, G2_09, G2_10,
        G2_11, G2_12, G2_13, G2_14, G2_15, G2_16, G2_17, G2_18, G2_19, G2_20,
        G2_21, G2_22,
    )
}


def smoke_test() -> None:
    from mmllm.aesop.curriculum.generator import generate_subject
    for sid, sub in SUBJECTS.items():
        recs = generate_subject(sub, n_per_example=1, seed=0)
        assert recs, f"no records for {sid}"
        for r in recs:
            assert r.tool_calls[0]["name"] == "eval"
    print(f"grade-2 fox-grapes smoke OK: {len(SUBJECTS)} subjects, "
          f"{sum(len(s.examples) for s in SUBJECTS.values())} examples")


if __name__ == "__main__":
    smoke_test()
