"""Emotion pools — complexity-graded and scenario-archetype.

Two families:

  Family A (EMO_P_EASY .. EMO_PH) maps polynomial-complexity bands
  to emotional vocabulary, so a grade-1 atom subject draws from
  P-easy ("calmly", "without effort") and a grade-12 macro subject
  draws from PH ("alternating between possibility and verification").

  Family B keeps the original scenario-archetype pools (PROUD,
  PATIENT, TIRED, etc.) at full size (>=30 each), plus 3 new pools
  (SUSPICIOUS, BOASTFUL, CAUTIOUS) that fill gaps in the
  fable-archetype space.

A subject at grade G picks one phrase from EMO_BAND_FOR_GRADE[G],
plus one phrase from a scenario-archetype pool picked by fable +
character. Templates can compose both into a sentence.
"""
from __future__ import annotations


# ─────────────────────── Family A: complexity bands ───────────────────────


EMO_P_EASY: tuple[str, ...] = (
    "calmly, without thinking",
    "without effort at all",
    "lightly, as if it were nothing",
    "as a matter of course",
    "as one notices the colour of the sky",
    "with the certainty of a known thing",
    "without even a pause",
    "the way one names a familiar friend",
    "easily, the answer plain",
    "as one breathes, without trouble",
    "with the ease of long habit",
    "as one greets the morning",
    "without troubling herself over it",
    "as plainly as the nose on her face",
    "with no more bother than blinking",
    "as if the answer had been waiting",
    "untroubled, the matter simple",
    "as one might remember a name",
    "with the small smile of certainty",
    "as a child names a colour",
    "without need of thought",
    "as if drawing breath",
    "with the calm of a settled day",
    "as one counts on familiar fingers",
    "the answer easy on her tongue",
    "without searching for it",
    "as plainly as one tells the time",
    "with the simple sureness of habit",
    "without the slightest furrow of thought",
    "as one knows the path home",
    "untroubled by any doubt",
    "as one names the colour of grass",
    "with the lightness of an old song",
    "easily, as one might hum",
)

EMO_P_MEDIUM: tuple[str, ...] = (
    "carefully, with measured attention",
    "with care, one piece at a time",
    "deliberately, taking her time",
    "step by step, attentively",
    "with the patience the work asked",
    "one operand attended to before the next",
    "attending to each part in its turn",
    "without rushing the answer",
    "weighing each piece honestly",
    "going slowly, that no step be missed",
    "with a careful hand and a careful mind",
    "minding each piece as it came",
    "letting one step settle before the next",
    "neither hurried nor idle",
    "keeping each operand in its proper place",
    "with the steady care of a slow worker",
    "taking up each part as it arrived",
    "putting one piece down before lifting the next",
    "not skipping a single step",
    "examining each piece with quiet attention",
    "as one shells peas one by one",
    "with the orderly mind of a careful child",
    "letting each thing have its turn",
    "with calm attention, piece by piece",
    "neither leaping ahead nor falling behind",
    "as one folds linen with care",
    "with the patience of an attentive student",
    "taking each operand on its own terms",
    "in the slow, certain rhythm of careful work",
    "minding the order, not skipping a turn",
    "with steady eyes and a steady hand",
    "weighing each part before moving on",
    "with the careful method of a baker",
)

EMO_P_HARD: tuple[str, ...] = (
    "methodically, fitting each piece",
    "composing the pieces in turn",
    "threading each step into the next",
    "as a craftsman fits joinery",
    "with the patience of someone who composes things in order",
    "letting each operation prepare the next",
    "stepping through the chain piece by piece",
    "as a weaver passes the shuttle",
    "with the orderly care of a millwright",
    "joining one piece to the next with quiet skill",
    "as a mason lays course upon course",
    "moving along the chain without losing her place",
    "fitting the work together, joint to joint",
    "as a smith hammers in steady time",
    "with the slow craft of fitting things together",
    "letting one outcome become the next input",
    "as a carpenter measures, marks, and cuts",
    "threading the operations like beads on a string",
    "with the methodical hand of a long apprenticeship",
    "stepping through the work as a millhand through the wheel",
    "linking each step to its neighbour",
    "with the careful order of a builder of stairs",
    "passing the result of one to the start of the next",
    "as a cooper sets stave to stave",
    "composing the chain of work without slip",
    "with the steady method of an old hand",
    "moving from step to step in measured order",
    "fitting each operation to the one before",
    "as a tinker sets one piece against another",
    "threading the work patiently together",
    "with the discipline of one who builds in order",
    "letting each step prepare the road for the next",
    "as a wheelwright fits spoke to hub",
)

EMO_NP: tuple[str, ...] = (
    "trying each candidate in turn",
    "considering one possibility, then another",
    "exploring options without commitment",
    "casting a net wide, hoping one would catch",
    "looking among many for the one that fit",
    "guessing, then verifying",
    "as one searches a forest for a particular leaf",
    "letting hope into the uncertainty of the search",
    "reaching first one way and then another",
    "as one tries every key on a heavy ring",
    "wandering among the possibilities",
    "hoping the next attempt would be the right one",
    "as a hunter casts about for a single track",
    "trying this, trying that, hoping one fit",
    "with the small hope that hides inside searching",
    "as one looks through a crowd for one face",
    "reaching for an answer that might or might not be there",
    "as a fisher tries one bend of the river, then another",
    "moving through the possibilities one by one",
    "with the hopeful patience of the searcher",
    "feeling for the right answer among many wrong ones",
    "as one gropes in a dark room for the latch",
    "guessing softly, then asking the world to confirm",
    "wading among the candidates",
    "as one tries every path of a branching wood",
    "with the slow patience of a long search",
    "leaving no candidate untried",
    "hoping, as searchers hope, for the matching piece",
    "as one shakes pebble after pebble from the shoe",
    "looking through the haystack for the slim bright needle",
    "lifting each stone in turn",
    "as one tastes broth after broth, seeking the right salt",
    "reaching among the maybes, hoping one would prove true",
)

EMO_CO_NP: tuple[str, ...] = (
    "checking each one against the rule",
    "ruling out the impossible",
    "ensuring all the cases were settled before claiming the answer",
    "with the rigor of someone who must answer for every case",
    "leaving no edge unchecked",
    "as a guard checks every gate",
    "weighing each case against the invariant",
    "answering for every possible turn of the matter",
    "as a steward counts every coin in the strongbox",
    "as a shepherd numbers every lamb at evening",
    "with the patience of one who closes every door",
    "settling every doubt before the answer was spoken",
    "verifying that no case had been overlooked",
    "as a miller checks every sack in the loft",
    "leaving no exception in the field",
    "as a watchman walks every length of the wall",
    "with the carefulness of one who must answer for all",
    "ensuring the rule held for every part",
    "as a clerk reads down every line of the ledger",
    "putting each case to the same hard test",
    "as a baker checks every loaf in the oven",
    "with the thoroughness of one who fears a missed case",
    "leaving no quiet corner unexamined",
    "as a gatekeeper turns away every one who fails",
    "asking the same question of every candidate",
    "as a judge weighs each side before speaking",
    "with the vigilance of one who must guarantee",
    "rounding the field, missing nothing",
    "as a fence-mender checks every panel",
    "settling every case, that none might rise later",
    "as a teacher marks every answer on the slate",
    "with the steady eye of one who must verify all",
    "asking, of each, whether the rule had held",
)

EMO_PH: tuple[str, ...] = (
    "alternating between possibility and verification",
    "weighing the search against the constraint",
    "asking, for every choice, whether some response existed",
    "as an architect weighs every floorplan against every life it might hold",
    "moving between the question and its checking, again and again",
    "balancing search and verification in alternation",
    "asking whether for every move there was a reply",
    "as a chess-master plays every line against every counter",
    "counting the operands twice, then once more",
    "considering, of each plan, whether some answer to it could fail",
    "as a strategist weighs every offense against every defense",
    "asking whether some path existed that survived every test",
    "as a councillor weighs each policy against each circumstance",
    "moving between exists and forall, layer upon layer",
    "as a cartographer weighs every road against every season",
    "asking, of every guess, whether some answer ruled it out",
    "with the alternating patience of those who reason in layers",
    "weighing each candidate against every objection it might face",
    "as a lawmaker tests every clause against every case it must serve",
    "moving up and down the ladder of question and answer",
    "asking, for every answer, whether some doubt remained",
    "as a watchful general balances every march against every ambush",
    "asking each question in turn, then the next",
    "considering, of each plan, every possible reply to every reply",
    "asking whether for every defence there existed an attack",
    "as a gardener weighs every season against every blight",
    "moving between the search for one and the demand of all",
    "balancing each maybe against every must",
    "as a master of games considers move and counter-move and counter-counter",
    "asking, of each rule, whether some case might escape it after all",
    "with eyes that miss nothing in the question",
    "weighing, again, what every answer might owe to every question",
    "as a careful mind moves between the some and the all",
)


# ─────────────────────── Family B: scenario archetypes ───────────────────────


EMO_PROUD: tuple[str, ...] = (
    "with a smug grin",
    "puffed up with pride",
    "as if the race were already won",
    "with great whoops of laughter",
    "boasting at every turn",
    "swaggering through the underbrush",
    "his chest thrown out before him",
    "sure of the win, head held high",
    "tossing his head as a proud horse tosses its mane",
    "with a laugh that carried over the field",
    "as one who has counted his victory before the running",
    "stepping high, as proud creatures step",
    "his nose lifted toward the bright sky",
    "as a victor walks before a victory is named",
    "with the easy swagger of a quick runner",
    "as if the matter were already settled in his favour",
    "with the loud bark of a sure winner",
    "his voice loud over the quiet road",
    "as if the prize already sat in his paw",
    "with the ringing pride of a hare among slow folk",
    "as one struts who has never yet been bested",
    "wearing his pride like a bright cloak",
    "with the clear ringing pride of the favoured",
    "as a young rooster crows above the yard",
    "his eyes bright with the joy of being first",
    "with the broad pride of a long-legged runner",
    "tossing back his ears as if to taunt the wind",
    "with the small pride of small triumphs already counted",
    "with quiet steps, taking the long way",
    "with the warm pride that goes before a fall",
    "his step bouncing with self-regard",
    "as a young captain walks before his first battle",
    "with a pride that filled him from ear-tip to heel",
)

EMO_PATIENT: tuple[str, ...] = (
    "without complaint or hurry",
    "saying very little",
    "with steady, careful steps",
    "with eyes always on the path",
    "untroubled by what others thought",
    "stepping deliberately, one foot before the next",
    "in the slow rhythm of one who knows the road",
    "with the patience that long roads teach",
    "as a tortoise walks, neither hurrying nor stopping",
    "her face quiet, her hands quieter still",
    "with a calm that nothing seemed to ruffle",
    "as one who has all the day before her",
    "with the steady breathing of a long walker",
    "as a millwheel turns, slow and sure",
    "neither hastening nor hanging back",
    "with the soft patience of running water",
    "as one waits who has waited many times before",
    "her steps unhurried, her mind clear",
    "with the unrushed care of a long task",
    "as the sun moves across the sky, slow and certain",
    "without raising her voice at the troubles of the road",
    "as a shepherd waits for the slow flock",
    "with the calm of long custom",
    "in the patient measure of one who knows the way",
    "her breath even, her step even, her thought even",
    "as a fisher waits beside the still pool",
    "neither restless nor weary, only steady",
    "with the slow grace of a creature unhurried",
    "keeping a steady pace through the work",
    "without lifting her voice or quickening her step",
    "with steady breath and a careful eye",
    "as a hen sits the long sit upon her eggs",
    "her quiet hands at her quiet sides",
)

EMO_TIRED: tuple[str, ...] = (
    "drowsy from the warm sun",
    "weary from the morning's effort",
    "lulled by the gentle wind",
    "with legs heavy from sprinting",
    "yawning at the soft moss",
    "her eyelids weighed down by the long day",
    "with the slow heaviness of a tired traveller",
    "his shoulders bent under the weight of the hours",
    "slowing the breath before the next step",
    "with the small sighs of one near sleep",
    "as a mower at the end of the field",
    "his head heavy upon his paws",
    "with the heaviness that comes after running",
    "blinking slow, as the tired blink",
    "his breath dragging in his chest",
    "with the dull weight of a long climb behind her",
    "as a horse drowses in the warm noon",
    "her every step costing more than the last",
    "resting one paw before lifting the next",
    "with the heavy quiet of weariness",
    "his mouth open, his breathing slow",
    "as a man at the end of the harvest day",
    "with shoulders that wished only to rest",
    "her eyelids dropping slow as evening petals",
    "as a tired child leans into a warm coat",
    "with limbs that asked only to be still",
    "taking the work one careful pace at a time",
    "his thoughts blurring at the edges with sleep",
    "with the dragging weariness of long travel",
    "with steady hands and an unhurried mind",
    "with the slow blink of a creature near rest",
    "his ears drooping, his tail still",
    "as one who has been too long awake",
)

EMO_THIRSTY: tuple[str, ...] = (
    "dry-throated and desperate",
    "parched from the long flight",
    "her beak cracked with thirst",
    "near to giving up the search for water",
    "with a thirst that hurt to bear",
    "her tongue rough as old bark",
    "with eyes that searched every shadow for water",
    "as one who has tasted only dust for hours",
    "her throat narrow with want of water",
    "with the dry voice of long thirst",
    "pausing where the road bent gently",
    "with lips cracked and breath shallow",
    "her every thought turning to a single drop",
    "with eyes set on the cool of the water",
    "with the burning thirst of a long noon",
    "her wings heavy from the dry sky",
    "as one who has long since drained her own waterskin",
    "with the parched fixity of a desperate searcher",
    "her tongue dry against the roof of her mouth",
    "as a flower in the seventh day of drought",
    "with the slow weakness that follows long thirst",
    "her beak wide, her breath dry",
    "as one who tastes salt where no salt was",
    "with eyes red and rimmed by the dry wind",
    "her thirst so deep it seemed a second hunger",
    "with patient wings, gliding low",
    "with the dry rattle of an empty gourd in her chest",
    "her every wingbeat asking for water",
    "as one whose thirst had dimmed every other care",
    "with the desperate hope of a creature near her last",
    "her thirst dragging at every step",
    "as a wanderer who has forgotten the taste of cold water",
    "with the hard-edged thirst of the long-flown",
)

EMO_HUNGRY: tuple[str, ...] = (
    "his stomach hollow with hunger",
    "her belly aching for food",
    "weak with hunger, his legs unsteady",
    "dreaming of the next meal",
    "with the gnawing emptiness of long want",
    "his ribs visible beneath thin fur",
    "as one who has not eaten since dawn",
    "with the dull insistence of an empty stomach",
    "her thoughts turning always to bread and broth",
    "as a beggar at the long lent gate",
    "with the slow ache of unfed days",
    "his hunger speaking louder than his manners",
    "as a winter wolf at the edge of the field",
    "with the hollow look of the long unfed",
    "her hunger sharpening every sense",
    "as one who tastes the air for any hint of supper",
    "with hunger like a quiet companion at her side",
    "his belly growling as a small thunder",
    "as a creature who counts the hours till feeding",
    "with the lean impatience of an empty stomach",
    "her hunger gnawing slow, then sharp",
    "as one whose last meal lay far behind",
    "with the heavy quiet of a hungry animal",
    "his eyes following every passing morsel",
    "as one whom hunger had taught to be patient",
    "with the kind of hunger that hollows the cheeks",
    "her stomach pleading more loudly than her tongue",
    "as a creature who would eat the wind if she could",
    "with hunger dragging at her every thought",
    "his hunger steady as a slow drumbeat",
    "as one for whom every smell was a torment",
    "with the deep hunger of an unfed week",
    "her hunger making her bold past her custom",
)

EMO_GREEDY: tuple[str, ...] = (
    "his eyes greedy with want",
    "with a hungry gleam in his eye",
    "imagining all that he might gain",
    "his thoughts already on more",
    "his mouth watering at the thought of more",
    "with the hard glitter of one who must have more",
    "as one whose hands were always reaching",
    "his fingers twitching at the thought of profit",
    "as a magpie eyes a brighter coin",
    "with greed like a small fire behind his ribs",
    "his gaze fastening on what was not yet his",
    "as one who counts another's purse before his own",
    "with the bright covetous look of the greedy",
    "his thoughts running on doubling and tripling",
    "as a miser tallies in his sleep",
    "his heart already in another man's storehouse",
    "with the sharp hunger that no meal mends",
    "as one whose enough was never enough",
    "his eye on every shining thing he passed",
    "with the cold appetite of unceasing want",
    "as a fox eyes the henhouse roof",
    "with greed running ahead of his good sense",
    "his hands already counting what he had not earned",
    "as one whose only measure was more",
    "with the slow secret smile of the covetous",
    "his thought leaping past the gift to the next gift",
    "as a crow turns a coin against the sun",
    "with the grasping look of the never-satisfied",
    "his mind already on the larger share",
    "as one who would weigh his neighbour's loaf",
    "with greed like a small worm at the heart",
    "his eyes wider than his stomach",
    "as a child who reaches for both apples at once",
)

EMO_CONTENT: tuple[str, ...] = (
    "happy with what she had",
    "pleased with her small fortune",
    "grateful for every bite",
    "content in her quiet life",
    "with the soft smile of one who wants no more",
    "as one who has measured her happiness and found it enough",
    "with the calm gladness of a settled heart",
    "as a cat sleeps in the warm window",
    "with the easy peace of a full bowl",
    "as one who counts her blessings and stops there",
    "with the deep quiet of one who needs nothing further",
    "as a hen on her own warm nest",
    "with the small sigh of a creature at peace",
    "as one whose day had given just enough",
    "with the steady gladness of long contentment",
    "as a household well-run and well-loved",
    "with the unhurried smile of the satisfied",
    "as one who measures her life and is glad of it",
    "with the calm of a finished task",
    "as a fire that burns low and warm",
    "with the soft happiness of an honest evening",
    "as one whose pockets held just enough",
    "with the bright contentment of a fair day",
    "as a child after a good supper",
    "with the steady joy of small enough sufficiencies",
    "as one whose wants had grown smaller than her share",
    "with the deep settle of an old chair",
    "as one whose hopes had ripened into thanks",
    "with the soft gladness of a kept hearth",
    "as a sheep grazing on her own hill",
    "with the warm certainty of a place that fit her",
    "as one who needed nothing the day did not bring",
    "with the gentle ease of a peaceful evening",
)

EMO_REGRETFUL: tuple[str, ...] = (
    "his heart sinking",
    "wishing she had been more careful",
    "regretting every careless step",
    "wondering how it had come to this",
    "with the slow ache of a wrong turn taken",
    "as one who looks back and counts the unlucky steps",
    "with regret like a stone in her chest",
    "her eyes turning back to what could not be undone",
    "with the hollow wish that she had chosen otherwise",
    "as one whose hands closed too late on what was lost",
    "with the soft sorrow of the late-wise",
    "her thoughts running back over every mistake",
    "as one who tastes the bitterness of her own choices",
    "with the slow grief of a chance let slip",
    "as a traveller who turns to find the road behind her gone",
    "with regret folding her like a cold cloak",
    "her chest tight with what she could not take back",
    "as one who has mended too late and found the cloth past saving",
    "with the dull pain of an undone good",
    "her every thought weighed by what might have been",
    "as a farmer counting the seed he scattered too soon",
    "with the slow shame of late understanding",
    "her hands empty of what they had once held",
    "as one who hears her own name in an old kindness",
    "with the small grief of an unsaid word",
    "as one who would give much to have said less",
    "with the heavy quiet of a regret too late to mend",
    "her face turned aside, lest it show too much",
    "as one whose own footprints had led her astray",
    "with the soft, late sorrow of the chastened",
    "her thoughts turning back to the fork in the road",
    "as one whose pride had cost her dearer than she could bear",
    "with the long ache of a thing done that could not be undone",
)

EMO_DESPERATE: tuple[str, ...] = (
    "with growing alarm",
    "wide-eyed with fear",
    "in a panic, hands trembling",
    "shouting until her voice cracked",
    "her hands trembling at her sides",
    "with the wild eye of one out of choices",
    "as one whose every plan had failed at once",
    "with the ragged breath of cornered hope",
    "her voice climbing past its usual reach",
    "as a creature pressed against the last wall",
    "with the trembling courage of the cornered",
    "her thoughts skittering for any way out",
    "as one whose calm had at last given way",
    "with the bright frantic eye of the desperate",
    "her hands working at anything she could grasp",
    "as a swimmer reaches for the last branch",
    "with breath that came short and sharp",
    "her heart hammering louder than her words",
    "as one who has run out of slow choices",
    "with the urgent quiet of a creature near breaking",
    "her every nerve drawn tight as a hard-pulled string",
    "as one who would try anything, anything at all",
    "with the high voice of a fear past hiding",
    "her thoughts narrowing to the one thing left",
    "as a fox at the end of the long chase",
    "with the trembling certainty that time was almost gone",
    "her breath coming in small cracked gasps",
    "as one for whom each second counted twice",
    "with the wide dark eyes of a cornered creature",
    "her words tumbling over each other in haste",
    "as one whose calm had broken open at last",
    "with hands that shook past her power to still them",
    "her heart loud as a bell in her ears",
)

EMO_SUSPICIOUS: tuple[str, ...] = (
    "with one eye narrowed to a slit",
    "her ears pricked for any wrong sound",
    "as one who hears wolves in every wind",
    "with a sideways look that gave nothing away",
    "her thoughts already at the worst guess",
    "as one who has been fooled before and remembers it",
    "with the wary stillness of a watched hare",
    "her glance flicking from face to face",
    "as a hen who has heard a fox at the wood's edge",
    "with the slow doubt of one who was once deceived",
    "her hand at her purse strings before he had spoken",
    "as one who counts the silver before the guests have left",
    "with the cool quiet of a careful disbeliever",
    "her brow furrowed at every smooth promise",
    "as a watchman who hears too many footsteps tonight",
    "with the small hard smile of the doubting",
    "her ears turned even toward what was not said",
    "as a shepherd who has heard false alarms before",
    "with the wary patience of one who waits to be lied to",
    "her thoughts running ahead of his words",
    "as one who weighs every gift for a hidden hook",
    "with the careful eye of a long-cheated woman",
    "her face still, her mind already at work",
    "as a goose who hears the thief before the dog does",
    "with the slow tilt of a head that has learned mistrust",
    "her glance never quite meeting his",
    "as one who waits for the second shoe to drop",
    "with the still wariness of a creature watched too often",
    "her ear bent for the false note in the song",
    "as a buyer who knows her merchant of old",
    "with the wary half-smile of the often-warned",
    "her thoughts already drawing the curtain",
    "as one who hears the wolf before he is seen",
)

EMO_BOASTFUL: tuple[str, ...] = (
    "loudly claiming the credit",
    "with a long story of his own merit",
    "as one whose tales had grown taller each telling",
    "with the broad voice of a bragging man",
    "his deeds painted larger than his deeds had been",
    "as a peacock who has practised every angle",
    "with a chest puffed past its proper size",
    "his every sentence beginning with himself",
    "as one whose own praise was his favourite song",
    "with the loud laugh of the self-pleased",
    "his name dropped between every other word",
    "as one whose modesty had long since worn through",
    "with the wide-armed gesture of the great teller",
    "his hand on his own breast in self-tribute",
    "as a herald who blew his own horn",
    "with the bright certainty of an accomplished bragger",
    "his account growing fuller with every listener",
    "as one whose feats outran any honest measure",
    "with the loud lift of one who must be heard",
    "his voice carrying over the whole tavern",
    "as a rooster crowing over a hen's good egg",
    "with a flourish at every mention of his name",
    "his deeds magnified in his own retelling",
    "as one who took the credit for the morning sun",
    "with the practised smile of a long-time boaster",
    "his stories growing horns and tails as he spoke",
    "as a man who had never met an exploit too small to enlarge",
    "with the wide pride of one who spares no detail",
    "his hand upon his medal, his eye upon the crowd",
    "as one whose own praises rolled easy from his tongue",
    "with the warm self-regard of a famous teller",
    "his name first in every story he told",
    "as one who had taken to his own legend",
)

EMO_CAUTIOUS: tuple[str, ...] = (
    "going slowly, looking twice at every step",
    "with the careful pace of one who hedges her bets",
    "checking the path before setting her foot",
    "as one who reads twice and signs only once",
    "with the slow hand of the double-checker",
    "her eyes on the ground for any loose stone",
    "as a fisher who tests the ice before crossing",
    "with the measured care of a careful borrower",
    "her hand always near a quick retreat",
    "as one who counts the coin twice before paying",
    "with the soft step of a guarded heart",
    "her decisions made slow and held lightly",
    "as a traveller who keeps the inn in sight",
    "with the considered pause of the cautious",
    "her plan built with a back door in it",
    "as one who folds the map before the rain",
    "with the careful hesitation of one who has tripped before",
    "her promise small, her care wide",
    "as a smith who tempers a blade twice over",
    "with the steady caution of a long-lived creature",
    "her hand on the rail of every stair she took",
    "as one who packs a candle for a sunny journey",
    "with the slow agreement of one who keeps a doubt in reserve",
    "her step soft, her attention wide",
    "as a tradesman who tries every coin against the stone",
    "with the small pause that goes before a wise word",
    "her eye on the weather and the road at once",
    "as one who feels for the floor in a strange house",
    "with the careful tread of a deer at the wood's edge",
    "her promises hedged with quiet conditions",
    "as a sailor who watches every cloud before sailing",
    "with the considered slowness of the twice-bitten",
    "her thoughts holding two outcomes at once",
)


# ─────────────────────── grade -> band lookup ───────────────────────


EMO_BAND_FOR_GRADE: dict[int, tuple[str, ...]] = {
    1:  EMO_P_EASY,
    2:  EMO_P_EASY,
    3:  EMO_P_MEDIUM,
    4:  EMO_P_MEDIUM,
    5:  EMO_P_MEDIUM,
    6:  EMO_P_HARD,
    7:  EMO_P_HARD,
    8:  EMO_NP,
    9:  EMO_CO_NP,
    10: EMO_CO_NP,
    11: EMO_PH,
    12: EMO_PH,
}


# ─────────────────────── smoke test ───────────────────────


def _smoke_test() -> None:
    band_pools = {
        "EMO_P_EASY":   EMO_P_EASY,   "EMO_P_MEDIUM": EMO_P_MEDIUM,
        "EMO_P_HARD":   EMO_P_HARD,   "EMO_NP":       EMO_NP,
        "EMO_CO_NP":    EMO_CO_NP,    "EMO_PH":       EMO_PH,
    }
    arch_pools = {
        "EMO_PROUD":    EMO_PROUD,    "EMO_PATIENT":  EMO_PATIENT,
        "EMO_TIRED":    EMO_TIRED,    "EMO_THIRSTY":  EMO_THIRSTY,
        "EMO_HUNGRY":   EMO_HUNGRY,   "EMO_GREEDY":   EMO_GREEDY,
        "EMO_CONTENT":  EMO_CONTENT,  "EMO_REGRETFUL": EMO_REGRETFUL,
        "EMO_DESPERATE": EMO_DESPERATE,
        "EMO_SUSPICIOUS": EMO_SUSPICIOUS,
        "EMO_BOASTFUL": EMO_BOASTFUL, "EMO_CAUTIOUS": EMO_CAUTIOUS,
    }
    for n, p in {**band_pools, **arch_pools}.items():
        assert len(p) >= 30, f"{n}: only {len(p)} entries"
        assert len(p) == len(set(p)), f"{n}: duplicates"
        assert all(isinstance(x, str) for x in p), f"{n}: non-str"
        assert all(3 <= len(x.split()) <= 14 for x in p), f"{n}: word-count out of range"
    assert set(EMO_BAND_FOR_GRADE.keys()) == set(range(1, 13))
    print(f"emotion_pools.py smoke_test: ok "
          f"({sum(len(p) for p in band_pools.values())} band entries, "
          f"{sum(len(p) for p in arch_pools.values())} archetype entries)")


if __name__ == "__main__":
    _smoke_test()
