"""Emotion pools — complexity-graded and scenario-archetype.

Two families:

  Family A (EMO_P_EASY .. EMO_PH) maps polynomial-complexity bands
  to emotional vocabulary, so a grade-1 atom subject draws from
  P-easy ("calmly", "without effort") and a grade-12 macro subject
  draws from PH ("alternating between possibility and verification").

  Family B keeps the original scenario-archetype pools (PROUD,
  PATIENT, TIRED, etc.) at full size (>=30 each), plus 3 new pools
  (SUSPICIOUS, BOASTFUL, CAUTIOUS) that fill gaps in the
  fable-archetype space.

A subject at grade G picks one phrase from EMO_BAND_FOR_GRADE[G],
plus one phrase from a scenario-archetype pool picked by fable +
character. Templates can compose both into a sentence.
"""
from __future__ import annotations


# ─────────────────────── Family A: complexity bands ───────────────────────


EMO_P_EASY: tuple[str, ...] = (
    "calmly without thinking",
    "without effort at all",
    "lightly as if nothing",
    "as a matter of course",
    "as one notices the colour of the sky",
    "with the certainty of a known thing",
    "without even a pause",
    "the way one names a familiar friend",
    "easily with the answer plain",
    "as untroubled as breathing",
    "with the ease of long habit",
    "as one greets the morning",
    "without troubling herself over it",
    "as plainly as the nose on her face",
    "with no more bother than blinking",
    "as if the answer had been waiting",
    "with the simple matter untroubled",
    "as one might remember a name",
    "with the small smile of certainty",
    "as a child names a colour",
    "without need of thought",
    "as if drawing breath",
    "with the calm of a settled day",
    "as one counts on familiar fingers",
    "the answer easy on her tongue",
    "without searching for it",
    "as plainly as one tells the time",
    "with the simple sureness of habit",
    "without the slightest furrow of thought",
    "as one knows the path home",
    "untroubled by any doubt",
    "as one names the colour of grass",
    "with the lightness of an old song",
    "easily as one might hum",
)

EMO_P_MEDIUM: tuple[str, ...] = (
    "with measured careful attention",
    "with care one piece at a time",
    "deliberately and taking her time",
    "step by step and attentively",
    "with the patience the work asked",
    "one operand attended to before the next",
    "attending to each part in its turn",
    "without rushing the answer",
    "weighing each piece honestly",
    "going slowly so no step is missed",
    "with a careful hand and a careful mind",
    "minding each piece as it came",
    "letting one step settle before the next",
    "neither hurried nor idle",
    "keeping each operand in its proper place",
    "with the steady care of a slow worker",
    "taking up each part as it arrived",
    "putting one piece down before lifting the next",
    "not skipping a single step",
    "examining each piece with quiet attention",
    "as one shells peas one by one",
    "with the orderly mind of a careful child",
    "letting each thing have its turn",
    "with calm attention piece by piece",
    "neither leaping ahead nor falling behind",
    "as one folds linen with care",
    "with the patience of an attentive student",
    "taking each operand on its own terms",
    "in the slow certain rhythm of careful work",
    "minding the order without skipping a turn",
    "with steady eyes and a steady hand",
    "weighing each part before moving on",
    "with the careful method of a baker",
)

EMO_P_HARD: tuple[str, ...] = (
    "methodically fitting each piece",
    "composing the pieces in turn",
    "threading each step into the next",
    "as a craftsman fits joinery",
    "with the patience of someone who composes things in order",
    "letting each operation prepare the next",
    "stepping through the chain piece by piece",
    "as a weaver passes the shuttle",
    "with the orderly care of a millwright",
    "joining one piece to the next with quiet skill",
    "as a mason lays course upon course",
    "moving along the chain without losing her place",
    "fitting the work together joint to joint",
    "as a smith hammers in steady time",
    "with the slow craft of fitting things together",
    "letting one outcome become the next input",
    "with a carpenter's measure-mark-cut",
    "threading the operations like beads on a string",
    "with the methodical hand of a long apprenticeship",
    "stepping through the work as a millhand through the wheel",
    "linking each step to its neighbour",
    "with the careful order of a builder of stairs",
    "passing the result of one to the start of the next",
    "as a cooper sets stave to stave",
    "composing the chain of work without slip",
    "with the steady method of an old hand",
    "moving from step to step in measured order",
    "fitting each operation to the one before",
    "as a tinker sets one piece against another",
    "threading the work patiently together",
    "with the careful order of a builder",
    "letting each step prepare the road for the next",
    "as a wheelwright fits spoke to hub",
)

EMO_NP: tuple[str, ...] = (
    "trying each candidate in turn",
    "considering one possibility then another",
    "exploring options without commitment",
    "casting a wide net hoping one would catch",
    "looking among many for the one that fit",
    "guessing and then verifying",
    "as one searches a forest for a particular leaf",
    "letting hope into the uncertainty of the search",
    "reaching first one way and then another",
    "as one tries every key on a heavy ring",
    "wandering among the possibilities",
    "hoping the next attempt would be the right one",
    "as a hunter casts about for a single track",
    "trying this and that hoping one fit",
    "with the small hope that hides inside searching",
    "as one looks through a crowd for one face",
    "reaching for an answer that might or might not be there",
    "as a fisher tries one river bend then another",
    "moving through the possibilities one by one",
    "with the hopeful patience of the searcher",
    "feeling for the right answer among many wrong ones",
    "as one gropes in a dark room for the latch",
    "guessing softly then asking for confirmation",
    "wading among the candidates",
    "as one tries every path of a branching wood",
    "with the slow patience of a long search",
    "leaving no candidate untried",
    "hoping as searchers hope for the matching piece",
    "as one shakes pebble after pebble from the shoe",
    "looking through the haystack for the slim bright needle",
    "lifting each stone in turn",
    "tasting broth after broth for the right salt",
    "reaching among the maybes hoping one would prove true",
)

EMO_CO_NP: tuple[str, ...] = (
    "checking each one against the rule",
    "ruling out the impossible",
    "ensuring all the cases were settled before claiming the answer",
    "with the rigor of someone who must answer for every case",
    "leaving no edge unchecked",
    "as a guard checks every gate",
    "weighing each case against the invariant",
    "answering for every possible turn of the matter",
    "as a steward counts every coin in the strongbox",
    "as a shepherd numbers every lamb at evening",
    "checking every door before moving on",
    "settling every doubt before the answer was spoken",
    "verifying that no case had been overlooked",
    "as a miller checks every sack in the loft",
    "leaving no exception in the field",
    "as a watchman walks every length of the wall",
    "answering for every step taken",
    "ensuring the rule held for every part",
    "as a clerk reads down every line of the ledger",
    "putting each case to the same hard test",
    "as a baker checks every loaf in the oven",
    "missing no corner of the work",
    "leaving no quiet corner unexamined",
    "as a gatekeeper turns away every one who fails",
    "asking the same question of every candidate",
    "as a judge weighs each side before speaking",
    "watchful for any wrong step",
    "rounding the field without missing",
    "as a fence-mender checks every panel",
    "settling every case so none might rise later",
    "as a teacher marks every answer on the slate",
    "with a steady eye checking each part",
    "asking of each whether the rule held",
)

EMO_PH: tuple[str, ...] = (
    "alternating between possibility and verification",
    "weighing the search against the constraint",
    "asking for every choice whether some response existed",
    "as an architect weighs every floorplan against every life it might hold",
    "moving repeatedly between question and checking",
    "balancing search and verification in alternation",
    "asking whether for every move there was a reply",
    "as a chess-master plays every line against every counter",
    "counting the operands twice and then once more",
    "considering of each plan whether some answer could fail",
    "as a strategist weighs every offense against every defense",
    "asking whether some path existed that survived every test",
    "as a councillor weighs each policy against each circumstance",
    "moving between exists and forall layer upon layer",
    "as a cartographer weighs every road against every season",
    "asking of every guess whether some answer ruled it out",
    "with the alternating patience of those who reason in layers",
    "weighing each candidate against every objection it might face",
    "as a lawmaker tests every clause against every case it must serve",
    "moving up and down the ladder of question and answer",
    "asking for every answer whether doubt remained",
    "as a watchful general balances every march against every ambush",
    "asking each question then the next in turn",
    "considering each plan with every possible reply",
    "asking whether for every defence there existed an attack",
    "as a gardener weighs every season against every blight",
    "moving between the search for one and the demand of all",
    "balancing each maybe against every must",
    "as a master of games considers move and counter-move and counter-counter",
    "asking of each rule whether some case might escape after all",
    "with eyes that miss nothing in the question",
    "weighing again what every answer might owe to every question",
    "as a careful mind moves between the some and the all",
)


# ─────────────────────── Family B: scenario archetypes ───────────────────────


EMO_PROUD: tuple[str, ...] = (
    "with a smug grin",
    "puffed up with pride",
    "as if the race were already won",
    "with great whoops of laughter",
    "boasting at every turn",
    "swaggering through the underbrush",
    "his chest thrown out before him",
    "sure of the win with head high",
    "tossing his head as a proud horse tosses its mane",
    "with a laugh that carried over the field",
    "carrying his head as one carrying the certainty of victory",
    "stepping high as proud creatures step",
    "his nose lifted toward the bright sky",
    "as a victor walks before a victory is named",
    "with the easy swagger of a quick runner",
    "as if the matter were already settled in his favour",
    "with the loud bark of a sure winner",
    "his voice loud over the quiet road",
    "as if the prize already sat in his paw",
    "with the ringing pride of a hare among slow folk",
    "as one struts who has never yet been bested",
    "wearing his pride like a bright cloak",
    "with the clear ringing pride of the favoured",
    "as a young rooster crows above the yard",
    "his eyes bright with the joy of being first",
    "with the broad pride of a long-legged runner",
    "tossing back his ears as if to taunt the wind",
    "with the small pride of small triumphs already counted",
    "with quiet steps taking the long way",
    "with the warm pride that goes before a fall",
    "his step bouncing with self-regard",
    "as a young captain walks before his first battle",
    "with a pride that filled him from ear-tip to heel",
)

EMO_PATIENT: tuple[str, ...] = (
    "without complaint or hurry",
    "saying very little",
    "with steady careful steps",
    "with eyes always on the path",
    "untroubled by what others thought",
    "stepping deliberately one foot before the next",
    "with steady road-tested feet",
    "with the patience that long roads teach",
    "with the steady walk of a tortoise",
    "with face quiet and hands quieter still",
    "with a calm that nothing seemed to ruffle",
    "with no need to hurry the work",
    "with the steady breathing of a long walker",
    "with the steady turn of a millwheel",
    "neither hastening nor hanging back",
    "with the soft patience of running water",
    "settled in for a long wait",
    "with unhurried steps and clear mind",
    "with the unrushed care of a long task",
    "with the slow certainty of the sun",
    "without raising her voice at the troubles of the road",
    "with the calm of a shepherd at his flock",
    "with the calm of long custom",
    "with the steady measure of a long walker",
    "with even breath and steady step",
    "with the still patience of a fisher",
    "neither restless nor weary but steady",
    "with the slow grace of a creature unhurried",
    "keeping a steady pace through the work",
    "without lifting her voice or quickening her step",
    "with steady breath and a careful eye",
    "with a hen's long stillness on the nest",
    "her quiet hands at her quiet sides",
)

EMO_TIRED: tuple[str, ...] = (
    "drowsy from the warm sun",
    "weary from the morning's effort",
    "lulled by the gentle wind",
    "with legs heavy from sprinting",
    "yawning at the soft moss",
    "her eyelids weighed down by the long day",
    "with the slow heaviness of a tired traveller",
    "his shoulders bent under the weight of the hours",
    "slowing the breath before the next step",
    "with the small sighs of one near sleep",
    "as a mower at the end of the field",
    "his head heavy upon his paws",
    "with the heaviness that comes after running",
    "blinking slow as tired creatures blink",
    "his breath dragging in his chest",
    "with the dull weight of a long climb behind her",
    "as a horse drowses in the warm noon",
    "her every step costing more than the last",
    "resting one paw before lifting the next",
    "with the heavy quiet of weariness",
    "with mouth open and breathing slow",
    "as a man at the end of the harvest day",
    "with shoulders that wished only to rest",
    "her eyelids dropping slow as evening petals",
    "as a tired child leans into a warm coat",
    "with limbs that asked only to be still",
    "taking the work one careful pace at a time",
    "his thoughts blurring at the edges with sleep",
    "with the dragging weariness of long travel",
    "with steady hands and an unhurried mind",
    "with the slow blink of a creature near rest",
    "with ears drooping and tail still",
    "with steady slow steps and tired eyes",
)

EMO_THIRSTY: tuple[str, ...] = (
    "dry-throated and desperate",
    "parched from the long flight",
    "her beak cracked with thirst",
    "near to giving up the search for water",
    "with a thirst that hurt to bear",
    "her tongue rough as old bark",
    "with eyes that searched every shadow for water",
    "with a dry tongue and a steady eye",
    "her throat narrow with want of water",
    "with the dry voice of long thirst",
    "pausing where the road bent gently",
    "with lips cracked and breath shallow",
    "her every thought turning to a single drop",
    "with eyes set on the cool of the water",
    "with the burning thirst of a long noon",
    "her wings heavy from the dry sky",
    "with the empty skin slung at her hip",
    "with the parched fixity of a desperate searcher",
    "her tongue dry against the roof of her mouth",
    "as a flower in the seventh day of drought",
    "with the slow weakness that follows long thirst",
    "with wide beak and dry breath",
    "feeling the salt that is not there",
    "with eyes red and rimmed by the dry wind",
    "her thirst so deep it seemed a second hunger",
    "with patient wings gliding low",
    "with the dry rattle of an empty gourd in her chest",
    "her every wingbeat asking for water",
    "with thirst close enough to crowd out the rest",
    "with the desperate hope of a creature near her last",
    "her thirst dragging at every step",
    "with a long-dried memory of cool water",
    "with the hard-edged thirst of the long-flown",
)

EMO_HUNGRY: tuple[str, ...] = (
    "his stomach hollow with hunger",
    "her belly aching for food",
    "weak with hunger and legs unsteady",
    "dreaming of the next meal",
    "with the gnawing emptiness of long want",
    "his ribs visible beneath thin fur",
    "with an empty stomach since dawn",
    "with the dull insistence of an empty stomach",
    "her thoughts turning always to bread and broth",
    "as a beggar at the long lent gate",
    "with the slow ache of unfed days",
    "his hunger speaking louder than his manners",
    "as a winter wolf at the edge of the field",
    "with the hollow look of the long unfed",
    "her hunger sharpening every sense",
    "sniffing the air for any hint of supper",
    "with hunger like a quiet companion at her side",
    "his belly growling as a small thunder",
    "counting the hours till the next meal",
    "with the lean impatience of an empty stomach",
    "her hunger gnawing slow then sharp",
    "with the last meal far behind her",
    "with the heavy quiet of a hungry animal",
    "his eyes following every passing morsel",
    "taught patience by long hunger",
    "with the kind of hunger that hollows the cheeks",
    "her stomach pleading more loudly than her tongue",
    "hungry enough to eat the wind",
    "with hunger dragging at her every thought",
    "his hunger steady as a slow drumbeat",
    "as one for whom every smell was a torment",
    "with the deep hunger of an unfed week",
    "her hunger making her bold past her custom",
)

EMO_GREEDY: tuple[str, ...] = (
    "his eyes greedy with want",
    "with a hungry gleam in his eye",
    "imagining all that he might gain",
    "his thoughts already on more",
    "his mouth watering at the thought of more",
    "with hard hungry eyes",
    "with hands always reaching",
    "his fingers twitching at the thought of profit",
    "as a magpie eyes a brighter coin",
    "with greed like a small fire behind his ribs",
    "his gaze fastening on what was not yet his",
    "counting another's purse before his own",
    "with the bright covetous look of the greedy",
    "his thoughts running on doubling and tripling",
    "as a miser tallies in his sleep",
    "his heart already in another man's storehouse",
    "with the sharp hunger that no meal mends",
    "with no enough that was ever enough",
    "his eye on every shining thing he passed",
    "with the cold appetite of unceasing want",
    "as a fox eyes the henhouse roof",
    "with greed running ahead of his good sense",
    "his hands already counting what he had not earned",
    "with only one measure: more",
    "with the slow secret smile of the covetous",
    "his thought leaping past the gift to the next gift",
    "as a crow turns a coin against the sun",
    "with the grasping look of the never-satisfied",
    "his mind already on the larger share",
    "weighing his neighbour's loaf in his eye",
    "with greed like a small worm at the heart",
    "his eyes wider than his stomach",
    "reaching for both apples at once",
)

EMO_CONTENT: tuple[str, ...] = (
    "happy with what she had",
    "pleased with her small fortune",
    "grateful for every bite",
    "content in her quiet life",
    "with a soft satisfied smile",
    "her happiness measured and enough",
    "with the calm gladness of a settled heart",
    "as a cat sleeps in the warm window",
    "with the easy peace of a full bowl",
    "with her blessings counted and the count enough",
    "with a deep finished quiet",
    "as a hen on her own warm nest",
    "with the small sigh of a creature at peace",
    "her day with just enough",
    "with the steady gladness of long contentment",
    "as a household well-run and well-loved",
    "with the unhurried smile of the satisfied",
    "glad of the life she had measured out",
    "with the calm of a finished task",
    "as a fire that burns low and warm",
    "with the soft happiness of an honest evening",
    "her pockets carrying just enough",
    "with the bright contentment of a fair day",
    "as a child after a good supper",
    "with the steady joy of small enough sufficiencies",
    "her wants smaller than her share",
    "with the deep settle of an old chair",
    "her hopes ripened into thanks",
    "with the soft gladness of a kept hearth",
    "as a sheep grazing on her own hill",
    "with the warm certainty of a place that fit her",
    "needing only what the day brought",
    "with the gentle ease of a peaceful evening",
)

EMO_REGRETFUL: tuple[str, ...] = (
    "his heart sinking",
    "wishing she had been more careful",
    "regretting every careless step",
    "wondering how it had come to this",
    "with the slow ache of a wrong turn taken",
    "looking back at unlucky steps",
    "with regret like a stone in her chest",
    "her eyes turning back to what could not be undone",
    "with the hollow wish that she had chosen otherwise",
    "her hands closing too late",
    "with the soft sorrow of the late-wise",
    "her thoughts running back over every mistake",
    "tasting the bitterness of her choices",
    "with the slow grief of a chance let slip",
    "with the lost-traveller look at a vanished road",
    "with regret folding her like a cold cloak",
    "her chest tight with what she could not take back",
    "mending too late with the cloth past saving",
    "with the dull pain of an undone good",
    "her every thought weighed by what might have been",
    "as a farmer counting the seed he scattered too soon",
    "with the slow shame of late understanding",
    "her hands empty of what they had once held",
    "hearing her own name in an old kindness",
    "with the small grief of an unsaid word",
    "wishing to have said less",
    "with the heavy quiet of a regret too late to mend",
    "her face turned aside lest it show too much",
    "her own footprints leading her astray",
    "with the soft late sorrow of the chastened",
    "her thoughts turning back to the fork in the road",
    "her pride costing more than she could bear",
    "with the long ache of a thing done that could not be undone",
)

EMO_DESPERATE: tuple[str, ...] = (
    "with growing alarm",
    "wide-eyed with fear",
    "in a panic with hands trembling",
    "shouting until her voice cracked",
    "her hands trembling at her sides",
    "with the wild eye of one out of choices",
    "every plan failed at once",
    "with the ragged breath of cornered hope",
    "her voice climbing past its usual reach",
    "as a creature pressed against the last wall",
    "with the trembling courage of the cornered",
    "her thoughts skittering for any way out",
    "her calm finally giving way",
    "with the bright frantic eye of the desperate",
    "her hands working at anything she could grasp",
    "as a swimmer reaches for the last branch",
    "with breath that came short and sharp",
    "her heart hammering louder than her words",
    "out of slow choices",
    "with the urgent quiet of a creature near breaking",
    "her every nerve drawn tight as a hard-pulled string",
    "ready to try anything",
    "with the high voice of a fear past hiding",
    "her thoughts narrowing to the one thing left",
    "as a fox at the end of the long chase",
    "with the trembling certainty that time was almost gone",
    "her breath coming in small cracked gasps",
    "as one for whom each second counted twice",
    "with the wide dark eyes of a cornered creature",
    "her words tumbling over each other in haste",
    "her calm broken open at last",
    "with hands that shook past her power to still them",
    "her heart loud as a bell in her ears",
)

EMO_SUSPICIOUS: tuple[str, ...] = (
    "with one eye narrowed to a slit",
    "her ears pricked for any wrong sound",
    "hearing wolves in every wind",
    "with a sideways look that gave nothing away",
    "her thoughts already at the worst guess",
    "fooled-before and remembering it",
    "with the wary stillness of a watched hare",
    "her glance flicking from face to face",
    "with a hen's listening",
    "with slow once-deceived doubt",
    "her hand at her purse strings before he had spoken",
    "counting silver before the guests leave",
    "with the cool quiet of a careful disbeliever",
    "her brow furrowed at every smooth promise",
    "with a watchman's wary listening",
    "with the small hard smile of the doubting",
    "her ears turned even toward what was not said",
    "with a shepherd's caution",
    "with the wary patience of someone expecting a lie",
    "her thoughts running ahead of his words",
    "weighing every gift for a hook",
    "with the careful eye of a long-cheated woman",
    "with her face still and her mind already at work",
    "with a goose's sharp ear",
    "with the slow tilt of a head that has learned mistrust",
    "her glance never quite meeting his",
    "waiting for the second shoe to drop",
    "with the still wariness of a creature watched too often",
    "her ear bent for the false note in the song",
    "with a long-time buyer's wariness",
    "with the wary half-smile of the often-warned",
    "her thoughts already drawing the curtain",
    "hearing the wolf before he is seen",
)

EMO_BOASTFUL: tuple[str, ...] = (
    "loudly claiming the credit",
    "with a long story of his own merit",
    "his tales taller each telling",
    "with the broad voice of a bragging man",
    "his deeds painted larger than his deeds had been",
    "with a peacock's careful angles",
    "with a chest puffed past its proper size",
    "his every sentence beginning with himself",
    "his own praise his favourite song",
    "with the loud laugh of the self-pleased",
    "his name dropped between every other word",
    "his modesty long since worn through",
    "with the wide-armed gesture of the great teller",
    "his hand on his own breast in self-tribute",
    "with a herald's loud horn",
    "with the bright certainty of an accomplished bragger",
    "his account growing fuller with every listener",
    "his feats outrunning any honest measure",
    "with the loud lift of someone needing to be heard",
    "his voice carrying over the whole tavern",
    "as a rooster crowing over a hen's good egg",
    "with a flourish at every mention of his name",
    "his deeds magnified in his own retelling",
    "taking credit for the morning sun",
    "with the practised smile of a long-time boaster",
    "his stories growing horns and tails as he spoke",
    "with no exploit too small to enlarge",
    "with wide pride — spares no detail",
    "with his hand upon his medal and his eye upon the crowd",
    "with own praises rolled easy from his tongue",
    "with the warm self-regard of a famous teller",
    "his name first in every story he told",
    "in the manner of had taken to his own legend",
)

EMO_CAUTIOUS: tuple[str, ...] = (
    "going slowly and looking twice at every step",
    "with careful pace — hedges her bets",
    "checking the path before setting her foot",
    "in the manner of reads twice and signs only once",
    "with the slow hand of the double-checker",
    "her eyes on the ground for any loose stone",
    "with a fisher's manner: tests the ice before crossing",
    "with the measured care of a careful borrower",
    "her hand always near a quick retreat",
    "in the manner of counts the coin twice before paying",
    "with the soft step of a guarded heart",
    "her decisions made slow and held lightly",
    "with a traveller's manner: keeps the inn in sight",
    "with the considered pause of the cautious",
    "her plan built with a back door in it",
    "in the manner of folds the map before the rain",
    "with careful hesitation — has tripped before",
    "with her promise small and her care wide",
    "with a smith's manner: tempers a blade twice over",
    "with the steady caution of a long-lived creature",
    "her hand on the rail of every stair she took",
    "in the manner of packs a candle for a sunny journey",
    "with slow agreement — keeps a doubt in reserve",
    "with her step soft and her attention wide",
    "with a tradesman's manner: tries every coin against the stone",
    "with the small pause that goes before a wise word",
    "her eye on the weather and the road at once",
    "in the manner of feels for the floor in a strange house",
    "with the careful tread of a deer at the wood's edge",
    "her promises hedged with quiet conditions",
    "with a sailor's manner: watches every cloud before sailing",
    "with the considered slowness of the twice-bitten",
    "her thoughts holding two outcomes at once",
)


# ─────────────────────── grade -> band lookup ───────────────────────


EMO_BAND_FOR_GRADE: dict[int, tuple[str, ...]] = {
    1:  EMO_P_EASY,
    2:  EMO_P_EASY,
    3:  EMO_P_MEDIUM,
    4:  EMO_P_MEDIUM,
    5:  EMO_P_MEDIUM,
    6:  EMO_P_HARD,
    7:  EMO_P_HARD,
    8:  EMO_NP,
    9:  EMO_CO_NP,
    10: EMO_CO_NP,
    11: EMO_PH,
    12: EMO_PH,
}


# ─────────────────────── smoke test ───────────────────────


def _smoke_test() -> None:
    band_pools = {
        "EMO_P_EASY":   EMO_P_EASY,   "EMO_P_MEDIUM": EMO_P_MEDIUM,
        "EMO_P_HARD":   EMO_P_HARD,   "EMO_NP":       EMO_NP,
        "EMO_CO_NP":    EMO_CO_NP,    "EMO_PH":       EMO_PH,
    }
    arch_pools = {
        "EMO_PROUD":    EMO_PROUD,    "EMO_PATIENT":  EMO_PATIENT,
        "EMO_TIRED":    EMO_TIRED,    "EMO_THIRSTY":  EMO_THIRSTY,
        "EMO_HUNGRY":   EMO_HUNGRY,   "EMO_GREEDY":   EMO_GREEDY,
        "EMO_CONTENT":  EMO_CONTENT,  "EMO_REGRETFUL": EMO_REGRETFUL,
        "EMO_DESPERATE": EMO_DESPERATE,
        "EMO_SUSPICIOUS": EMO_SUSPICIOUS,
        "EMO_BOASTFUL": EMO_BOASTFUL, "EMO_CAUTIOUS": EMO_CAUTIOUS,
    }
    for n, p in {**band_pools, **arch_pools}.items():
        assert len(p) >= 30, f"{n}: only {len(p)} entries"
        assert len(p) == len(set(p)), f"{n}: duplicates"
        assert all(isinstance(x, str) for x in p), f"{n}: non-str"
        assert all(3 <= len(x.split()) <= 14 for x in p), f"{n}: word-count out of range"
    assert set(EMO_BAND_FOR_GRADE.keys()) == set(range(1, 13))
    print(f"emotion_pools.py smoke_test: ok "
          f"({sum(len(p) for p in band_pools.values())} band entries, "
          f"{sum(len(p) for p in arch_pools.values())} archetype entries)")


if __name__ == "__main__":
    _smoke_test()
