(ns mmllm.jvm.params
  "Load the arch manifest + dense params + banks into JVM structures.

   - manifest: jvm/resources/arch-sym24.edn (generated by scripts/jvm_bridge.py)
   - dense:    dense.npz with positional keys d00000.. (bridge to-npz output,
               or jvm/goldens/dense.npz)
   - banks:    raw headerless .bin (native layout) via FileChannel mmap"
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [mmllm.jvm.npy :as npy]
            [mmllm.jvm.rowstore]
            [mmllm.jvm.tensor :as t])
  (:import [java.nio ByteOrder]
           [java.nio.channels FileChannel FileChannel$MapMode]
           [java.nio.file Paths StandardOpenOption]
           [mmllm.jvm.rowstore IRowStore]))

(set! *warn-on-reflection* true)

(defn load-manifest [path]
  (let [m (edn/read-string (slurp path))]
    (assert (= "sym24" (:arch m)) (str "unexpected arch " (:arch m)))
    m))

(defn load-dense
  "-> {:by-name {name tensor} :by-index [tensor ...]}, shape-checked
   against the manifest."
  [manifest npz-path]
  (let [z (npy/read-npz npz-path)
        n (long (:n_dense_tensors manifest))]
    (assert (= n (count z)) (str "dense.npz has " (count z) " tensors, manifest says " n))
    (let [by-index
          (mapv (fn [{:keys [index name shape]}]
                  (let [ten (t/from-npy (clojure.core/get z (format "d%05d" (long index))))]
                    (assert (= (mapv long shape) (mapv long (:shape ten)))
                            (str name " shape " (:shape ten) " != manifest " shape))
                    ten))
                (:dense manifest))]
      {:by-index by-index
       :by-name (zipmap (map :name (:dense manifest)) by-index)})))

(defn map-bank
  "mmap a raw bank .bin as a read/write little-endian FloatBuffer of
   (rows, dim). fp32 only (the sym24 chain's V dtype)."
  [path rows dim]
  (let [p (Paths/get (str path) (make-array String 0))
        ch (FileChannel/open p (into-array StandardOpenOption
                                           [StandardOpenOption/READ StandardOpenOption/WRITE]))
        want (* 4 (long rows) (long dim))
        size (.size ch)]
    (assert (= size want) (str path " is " size " bytes; expected " want
                               " for (" rows "," dim ") fp32"))
    (let [buf (.map ch FileChannel$MapMode/READ_WRITE 0 size)]
      (.order buf ByteOrder/LITTLE_ENDIAN)
      {:path (str path) :rows (long rows) :dim (long dim)
       :fb (.asFloatBuffer buf) :mbb buf :channel ch})))

(defn bank-row!
  "Copy row i of a mapped bank into out (float[dim]) at out-off.

   Banks may carry an OVERLAY (:overlay — a packed IRowStore, or
   back-compat a java.util.Map of row → float[dim]) holding in-RAM
   updates that shadow the mmap'd file. The parity gates' training
   replays write their optimizer updates there so the golden .bin files
   are never mutated. The spoon trainer instead mmaps SCRATCH COPIES of
   the banks with :writable? true and no overlay (bank-put-row! writes
   the file mapping directly). A bank marked :zero? reads as all-zero
   rows — the ablation-eval hook (evals.clj); the file is untouched."
  [{:keys [^java.nio.FloatBuffer fb ^long dim overlay zero?]} ^long i ^floats out ^long out-off]
  (if zero?
    (java.util.Arrays/fill out (int out-off) (int (+ out-off dim)) (float 0.0))
    (let [hit (cond
                (nil? overlay) false
                (instance? IRowStore overlay)
                (.rsCopyRow ^IRowStore overlay i out out-off)
                :else
                (if-let [^floats row (.get ^java.util.Map overlay i)]
                  (do (System/arraycopy row 0 out (int out-off) (int dim)) true)
                  false))]
      (when-not hit
        (let [fb (.duplicate fb)]
          (.position fb (* i dim))
          (.get fb out (int out-off) (int dim)))))))

(defn bank-put-row!
  "Write row i: into the bank's overlay when it has one (values copied;
   the mmap'd file is never written — the parity-gate mode), or straight
   into the file mapping when the bank was opened :writable? (the spoon
   trainer's scratch-copy mode)."
  [{:keys [^java.nio.FloatBuffer fb ^long dim overlay writable?]} ^long i ^floats row]
  (cond
    overlay
    (if (instance? IRowStore overlay)
      (.rsPutRow ^IRowStore overlay i row 0)
      (.put ^java.util.Map overlay i (java.util.Arrays/copyOf row (int dim))))
    writable?
    (let [b (.duplicate fb)]
      (.position b (int (* i dim)))
      (.put b row 0 (int dim)))
    :else
    (throw (IllegalStateException.
            "bank-put-row! needs a bank opened with an :overlay or :writable?"))))

(defn load-banks
  "Open every bank listed in the manifest's :sparse from `dir`
   -> {name mapped-bank}."
  [manifest dir]
  (into {}
        (for [{:keys [name file shape]} (:sparse manifest)]
          [name (map-bank (io/file dir file) (first shape) (second shape))])))
