(ns mmllm.jvm.params
  "Load the arch manifest + dense params + banks into JVM structures.

   - manifest: jvm/resources/arch-sym24.edn (generated by scripts/jvm_bridge.py)
   - dense:    dense.npz with positional keys d00000.. (bridge to-npz output,
               or jvm/goldens/dense.npz)
   - banks:    raw headerless .bin (native layout) via FileChannel mmap"
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [mmllm.jvm.npy :as npy]
            [mmllm.jvm.tensor :as t])
  (:import [java.nio ByteOrder]
           [java.nio.channels FileChannel FileChannel$MapMode]
           [java.nio.file Paths StandardOpenOption]))

(set! *warn-on-reflection* true)

(defn load-manifest [path]
  (let [m (edn/read-string (slurp path))]
    (assert (= "sym24" (:arch m)) (str "unexpected arch " (:arch m)))
    m))

(defn load-dense
  "-> {:by-name {name tensor} :by-index [tensor ...]}, shape-checked
   against the manifest."
  [manifest npz-path]
  (let [z (npy/read-npz npz-path)
        n (long (:n_dense_tensors manifest))]
    (assert (= n (count z)) (str "dense.npz has " (count z) " tensors, manifest says " n))
    (let [by-index
          (mapv (fn [{:keys [index name shape]}]
                  (let [ten (t/from-npy (clojure.core/get z (format "d%05d" (long index))))]
                    (assert (= (mapv long shape) (mapv long (:shape ten)))
                            (str name " shape " (:shape ten) " != manifest " shape))
                    ten))
                (:dense manifest))]
      {:by-index by-index
       :by-name (zipmap (map :name (:dense manifest)) by-index)})))

(defn map-bank
  "mmap a raw bank .bin as a read/write little-endian FloatBuffer of
   (rows, dim). fp32 only (the sym24 chain's V dtype)."
  [path rows dim]
  (let [p (Paths/get (str path) (make-array String 0))
        ch (FileChannel/open p (into-array StandardOpenOption
                                           [StandardOpenOption/READ StandardOpenOption/WRITE]))
        want (* 4 (long rows) (long dim))
        size (.size ch)]
    (assert (= size want) (str path " is " size " bytes; expected " want
                               " for (" rows "," dim ") fp32"))
    (let [buf (.map ch FileChannel$MapMode/READ_WRITE 0 size)]
      (.order buf ByteOrder/LITTLE_ENDIAN)
      {:path (str path) :rows (long rows) :dim (long dim)
       :fb (.asFloatBuffer buf) :channel ch})))

(defn bank-row!
  "Copy row i of a mapped bank into out (float[dim]) at out-off.

   Banks may carry an OVERLAY (:overlay, a java.util.HashMap of row →
   float[dim]) holding in-RAM updates that shadow the mmap'd file. The
   training replay (mmllm.jvm.train-step) writes its optimizer updates
   there so the golden .bin files are never mutated; eval paths that
   load banks without an overlay are unaffected."
  [{:keys [^java.nio.FloatBuffer fb ^long dim overlay]} ^long i ^floats out ^long out-off]
  (if-let [^floats row (when overlay (.get ^java.util.HashMap overlay i))]
    (System/arraycopy row 0 out (int out-off) (int dim))
    (let [fb (.duplicate fb)]
      (.position fb (* i dim))
      (.get fb out (int out-off) (int dim)))))

(defn bank-put-row!
  "Write row i into the bank's overlay (row values copied). The mmap'd
   file itself is never written — see bank-row!'s overlay note."
  [{:keys [^long dim overlay]} ^long i ^floats row]
  (assert overlay "bank-put-row! needs a bank opened with an :overlay")
  (.put ^java.util.HashMap overlay i
        (java.util.Arrays/copyOf row (int dim))))

(defn load-banks
  "Open every bank listed in the manifest's :sparse from `dir`
   -> {name mapped-bank}."
  [manifest dir]
  (into {}
        (for [{:keys [name file shape]} (:sparse manifest)]
          [name (map-bank (io/file dir file) (first shape) (second shape))])))
