"""Cross-fable showcase: same K-12 Clojure subject rendered through
all 5 Phase-C-complete fables.

Each row picks a representative subject from the K-12 framework;
columns show that same subject's first example told through
tortoise-hare, crow-pitcher, milkmaid, boy-wolf, and dog-shadow.
This demonstrates the breadth of the corpus: ~750K records the
model trains on are generated by varying these scenarios across
character / location / emotion / opener / template pools — one
form, five fable lenses, dozens of narrative beats.

Output: docs/clojure-pedagogy/audits/showcase-five-fables.md
"""
import importlib
import sys

sys.path.insert(0, "/home/user/mmllm/src")

from mmllm.aesop.curriculum.generator import generate_subject

# 13 subjects spanning the K-12 hierarchy. One per grade; load-bearing
# pedagogical concepts.
SHOWCASE = [
    ("G1-01",  "L1 atom — a literal evaluates to itself"),
    ("G1-13",  "L2 application — first arithmetic call"),
    ("G2-13",  "and/or short-circuit — chain of gates"),
    ("G3-03",  "let — local binding (the temporary-pouch metaphor)"),
    ("G4-08",  "assoc — pin a tag on the basket"),
    ("G5-12",  "reduce — walk the row carrying a tally"),
    ("G6-03",  "require — borrow a routine from a foreign scroll"),
    ("G7-02",  "try / catch — net under the leap"),
    ("G8-04",  "Protocol definition — found a guild"),
    ("G9-03",  "Atom introduction — shared-state notebook"),
    ("G10-03", "defmacro — rule that rewrites the recipe"),
    ("G11-02", "Method call syntax — borrowed host tool"),
    ("G12-01", "Transducers — composable sieve"),
]

FABLES = [
    ("tortoise_hare",  "Tortoise and the Hare",      "vanity vs. steadiness"),
    ("crow_pitcher",   "Crow and the Pitcher",       "patience vs. thirst"),
    ("milkmaid",       "Milkmaid and her Pail",      "daydream vs. care"),
    ("boy_wolf",       "Boy who Cried Wolf",         "trust vs. false alarm"),
    ("dog_shadow",     "Dog and the Shadow",         "greed loses what was had"),
]


def get_subject(fable: str, sid: str):
    grade = int(sid.split("-")[0][1:])
    mod = importlib.import_module(
        f"mmllm.aesop.curriculum.{fable}.grade_{grade}")
    return mod.SUBJECTS.get(sid)


def render_first_example(fable: str, sid: str, seed: int):
    sub = get_subject(fable, sid)
    if sub is None:
        return None, None
    # Force a story-template render if available (sample seeds until
    # the story-template fires; otherwise fall back to first render).
    first_ex = sub.examples[0]
    if "story" in getattr(first_ex, "tags", ()) and first_ex.scenario:
        marker = first_ex.scenario.split(".")[0][:30]
        for s in range(seed, seed + 100):
            recs = generate_subject(sub, n_per_example=1, seed=s)
            if recs and marker in recs[0].user_msg:
                return sub, recs[0]
    recs = generate_subject(sub, n_per_example=1, seed=seed)
    return (sub, recs[0]) if recs else (sub, None)


def fence_form(s: str) -> str:
    if "`" in s:
        return f"`` {s} ``"
    return f"`{s}`"


OUT = "/home/user/mmllm/docs/clojure-pedagogy/audits/showcase-five-fables.md"

with open(OUT, "w") as f:
    f.write("# Cross-fable showcase — same K-12 Clojure subject through five fable lenses\n\n")
    f.write("Each row picks a load-bearing Clojure subject from the K-12\n")
    f.write("framework. The five columns are the five Phase-C-complete\n")
    f.write("fables on `main`: same form, same expected value, told through\n")
    f.write("each fable's own characters, locations, and metaphor imagery.\n\n")
    f.write("This is what the model sees at training time — for any one\n")
    f.write("Clojure form, dozens to hundreds of narrative variants per\n")
    f.write("fable × 5 fables = a deep saturation of the same idiom-to-\n")
    f.write("metaphor mapping across a corpus that reads like 5 distinct\n")
    f.write("storybooks teaching the same curriculum.\n\n")
    f.write("Atom subjects (G1-01) keep `_SHARED_SUBPLOTS` in every fable —\n")
    f.write("the form IS the answer; copy-from-prompt is the lesson, and\n")
    f.write("the form-display is intentionally shown.\n\n")
    f.write("Goal-style subjects render via the family pool's templates;\n")
    f.write("when an example has authored `scenario`/`need`/`mapping`/\n")
    f.write("`resolution` slots and `tags=(\"story\",)`, the 5-act\n")
    f.write("story-scaffold template fires and the metaphor *drives*\n")
    f.write("the action (vs. merely framing it).\n\n")
    f.write("The five fables and their morals:\n\n")
    for slug, name, moral in FABLES:
        f.write(f"- **{name}** — _{moral}_\n")
    f.write("\n---\n\n")

    for sid, label in SHOWCASE:
        f.write(f"## {sid} — {label}\n\n")

        for fable_dir, fable_name, _ in FABLES:
            seed = abs(hash((fable_dir, sid))) % (10**8)
            sub, rec = render_first_example(fable_dir, sid, seed)
            if rec is None:
                f.write(f"### {fable_name}\n\n")
                f.write(f"*(subject {sid} not in {fable_dir}'s curriculum)*\n\n")
                continue
            has_story = (
                "story" in getattr(sub.examples[0], "tags", ())
                and sub.examples[0].scenario
                and sub.examples[0].scenario.split(".")[0][:30] in rec.user_msg
            )
            tag = " — *story-scaffold render*" if has_story else ""
            f.write(f"### {fable_name}{tag}\n\n")
            f.write(f"**form**: {fence_form(rec.code_str)}  •  "
                    f"**expected**: `{rec.expected!r}`\n\n")
            f.write("````text\n")
            f.write(rec.user_msg.rstrip() + "\n\n---\n\n")
            f.write(rec.assistant_msg.rstrip() + "\n````\n\n")

        f.write("---\n\n")

print(f"wrote {OUT}")
